apiVersion: "autoscaling.openshift.io/v1beta1"
kind: "MachineAutoscaler"
metadata:
  name: "worker-us-east-1b" 
  namespace: "openshift-machine-api"
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef: 
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: cluster2-ngdf7-worker-us-east-1b
