apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- cluster3-mj5nw-worker-us-west-2a.yaml
- cluster3-mj5nw-worker-us-west-2b.yaml
- cluster3-mj5nw-worker-us-west-2c.yaml
