apiVersion: "autoscaling.openshift.io/v1beta1"
kind: "MachineAutoscaler"
metadata:
  name: "worker-us-west-2a"
  namespace: "openshift-machine-api"
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef: 
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: cluster3-mj5nw-worker-us-west-2a
