---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  creationTimestamp: null
  labels:
    app: pricelist
    tier: frontend
  name: pricelist
  namespace: pricelist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pricelist
      tier: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pricelist
        tier: frontend
    spec:
      containers:
      - image: quay.io/redhatworkshops/pricelist:latest
        name: pricelist
        resources: {}
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: pricelist-secret
              key: mysqldb
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pricelist-secret
              key: mysqlpass
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: pricelist-secret
              key: mysqluser
        - name: MYSQL_SERVICE_HOST
          valueFrom:
            secretKeyRef:
              name: pricelist-secret
              key: mysqlhost
        - name: MYSQL_SERVICE_PORT
          valueFrom:
            secretKeyRef:
              name: pricelist-secret
              key: mysqlport
...
