apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

bases:
- ../../base/

resources:
- ns.yaml
- cm.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: quarkus-app
  patch: |
    - op: replace
      path: /spec/replicas
      value: 3
