apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: quarkus
  version: 0.0.3
  repo: https://redhat-developer.github.io/redhat-helm-charts
  valuesFile: values.yaml
  releaseName: quarkus-app
  ## IF needed
  #includeCRDs: true
