apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: test
spec: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gobg
  name: gobg
  namespace: test
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gobg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gobg
  name: gobg
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobg
  strategy: {}
  template:
    metadata:
      labels:
        app: gobg
    spec:
      containers:
      - image: christianh814/gobg:latest
        name: gobg
        resources: {}